[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "py_online_forecast"
dynamic = ["version", "dependencies"]
description = "A package for online forecasting and hierarchical reconciliation"
readme = "README.md"
requires-python = ">=3.12.3"

[tool.setuptools]
package-dir = {"" = "."}
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["py_online_forecast*"]

[tool.setuptools.package-data]
py_online_forecast = ["requirements.txt"]

[tool.setuptools.dynamic]
version = {attr = "py_online_forecast.__version__"}
dependencies = {file = ["py_online_forecast/requirements.txt"]}

[tool.black]
line-length = 88
target-version = ["py312"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "D"]
ignore = [
  "D203",  # conflicts with D211
  "D213",  # conflicts with D212
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D"]
"**/test_*.py" = ["D"]